### PR TITLE
feat: completed the integration of applicationView

### PR DESCRIPTION
**Pull request by ibishal**
**Description**
In this PR I have integrated `ApplicationView` from EDAVisualizer with vs-async-preview, this is the initial PR of integration of EDAVisualiser into vs-async-preview 

[Screencast from 15-10-24 11:04:11 PM IST.webm](https://github.com/user-attachments/assets/62bd1530-1b6a-42ad-b134-0ad82cd07337)

**Related issue(s)**
Completed #234

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Amazing, let me know if anything needs to happen in EDAVisualizer, happy to help review and merge PRs with priority :slightly_smiling_face:

**Review by ivangsa — APPROVED** [review]
lgtm

**Review by ivangsa — APPROVED** [review]

**Pull request merged**
