### PR TITLE
Initial Setup of Markdown+Mermaid

### LINKED ISSUE #161: Alternative Preview Option with Markdown and MermaidJS Diagrams
Provide and alternative preview based on markdown that visualizes message payload as MermaidJS Class Diagrams

https://mermaid.js.org/syntax/classDiagram.html

- Support exporting this markdown preview as text so it can be included in external documentation
- It should support both asyncapi schema and and avro (.avsc files)
- It would be nice if scrolling between preview pannel and source code is kept in synch

### PR DESCRIPTION
**Pull request by nikhilkalburgi**
**Description**

- The Design for the new PreView Panel
image
- Created additional panel for markdown
- In the design I have included a copy button to export markdown 
- In the components folder we can develop the markdown of all asyncapi objects + mermaid diagram
- Using `markdown-it` to translate the markdown to HTML for preview
- Using `@asyncapi/parser` to parse and pass to individual functions in `./components `folder
- Added the mermaid script to render mermaid diagrams
- Need to work for a better UI
- `Info` is not fully developed, but needs more development to be done

**Tools Used:** mermaid.js, markdown-it, @asyncapi/parser

Hi @ivangsa , what do you think about this? also need to decide whether to go for flowchart or classdiagram. Once the setup is accepted, we can start the further developements

**Related issue(s)**
Partially Resolves #161

### CODE REVIEW

**Comment by ivangsa** [comment]
Good work!
can you collaborate with @josephinoo in creating a template, maybe with ejs, for the markdown content...
maybe including:
- info
- servers
- channels
- messages
And also a mermaid diagram for the schemas with relationships for each message (separated)

**Review by ivangsa — APPROVED** [review]
good work!

**Comment by ivangsa** [comment]
I'm merging this so you can collaborate on this

/rtm

**Comment by nikhilkalburgi** [comment]
Sure @ivangsa

**Congrats to you and entire community!** for being accepted as GSOC 24 Org.

**Pull request merged**
