### PR TITLE
Markdown + Mermaid template

### PR DESCRIPTION
**Pull request by josephinoo**
**Description**

- ETA TEMPLATE
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by josephinoo** [comment]
Hi @nikhilkalburgi, I am considering rendering using the ETA template and, instead of directly generating the markdown (MD), display the content in HTML format first. This way, we will be able to establish a clear relationship between the HTML and the corresponding MD. Also, we could include a button at the end to allow users to export the content in MD or even PDF format. What do you think ?
https://www.markdownguide.org/basic-syntax/

**Comment by nikhilkalburgi** [comment]
Hi @josephinoo,
That's a great Idea. We can also discuss this on **Slack** in details.
**In Short:**
1. We need to install Template engine like **EJS** or **ETA** to render HTML on preview
2. We need a tool to convert HTML to MD like Eg. **turndown** for **export**
3. Design the **prototype** for the **final UI** with options for export etc... (I have built the initial wireframe, but more to be done )
4. Build the individual objects like **servers, schema, operations, diagrams** by creating template files(.ejs or .eta) for each in the newly added `./components` folder.
5. Other issues like support for **avro** schema etc.

**Comment by nikhilkalburgi** [comment]
Hi @ivangsa @josephinoo,

Below you will find the prototype that I have designed on Figma 

https://github.com/asyncapi/vs-asyncapi-preview/assets/70331875/7e1919a5-514f-445c-bfd2-073c077bbb70

I would appreciate your input on this to improve it further.

I also tried to set the template engine ETA but found that it is not very compatible with VS Code Env. So, I have used EJS instead and have developed the project structure with it. Soon I will raise a PR.

**Comment by ivangsa** [comment]
hi @nikhilkalburgi 

I think the diagram in second 0:09 doesn`t make too much sense but it would require something similar for the payload of each message

I would create a separate one for each message, because maybe they are shared objects between messages and it's nice to to have everything mixed up..

I think EJS is good, it has more traction behind and ETA features are not that definitive for this usage..

**Comment by nikhilkalburgi** [comment]
Hi @ivangsa,

I had implemented it like below:

In **webpack.confi.js**:
```
plugins: [
    new CopyPlugin({
      patterns: [
                . . .
        {
                  from: 'src/components',
                  to: 'components'
        } 
      ]
```
This will copy the .ejs files in ./components folder into ./dist/components

then:

```
const templatePath = path.join(context.extensionPath,'dist', 'components','Asyncapi.ejs');
await ejs.renderFile(templatePath , { ... });
```

**But, now I am following your suggestion.**

Initially, I will build the markdown for the objects and later integrate the mermaid diagrams

**Comment by ivangsa** [comment]
@nikhilkalburgi if it works in all cases, development and packaged, don't need to change it..

**Comment by nikhilkalburgi** [comment]
> @nikhilkalburgi if it works in all cases, development and packaged, don't need to change it..

Okay!

**Pull request closed without merging**
