### PR TITLE
fix: update readme and trigger release under new owner

### PR DESCRIPTION
**Pull request by derberg**
Looks like the transfer was finally done -> https://marketplace.visualstudio.com/items?itemName=asyncapi.asyncapi-preview

@ivangsa approve please and we will see if release pipeline is fully operational 🤞🏼

### CODE REVIEW

**Review by ivangsa — APPROVED** [review]

**Comment by derberg** [comment]
@ivangsa yes! 0.3.7 is nicely released by our bots to:
- https://marketplace.visualstudio.com/items?itemName=asyncapi.asyncapi-preview
- https://marketplace.visualstudio.com/items?itemName=asyncapi.asyncapi-preview

💪🏼 💪🏼 💪🏼 

will you go through existing issues, mention new plugin location, that plugin got also refreshed, and that we close issues and they should recreate them if issue is still there?


did you also consider if you want to join AsyncAPI TSC?

**Comment by ivangsa** [comment]
great to hear!!

I confirm that the extension upgraded automatically and informed/closed existing issues..

And yes I will be happy to join the AsyncAPI TSC!

**Comment by derberg** [comment]
> And yes I will be happy to join the AsyncAPI TSC!

this is awesome, thanks 🙏🏼 

please just open a PR to add you to https://github.com/asyncapi/community/blob/master/TSC_MEMBERS.json file and open a PR like https://github.com/asyncapi/community/pull/360

**Pull request merged**
