### PR TITLE
docs: update instructions in the Readme.md

### LINKED ISSUE #143: Modify extension usage in README.md
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  This extensive is no longer working from context menu, users need to use other methods.
- How will this change help?
   Show user how to use it by updating README.md.
- What is the motivation? 
    I was confused when I first installed it, and it didn't work as I expected. 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
   Show correct way in README.md.
- Will this be a breaking change?
   Nope.
- How could it be implemented/designed?
   Just modify the README.md file.

### PR DESCRIPTION
**Pull request by luotianchun**
**Description**

- Update the README.md about how to use this extension in vscode.

**Related issue(s)**
  Resolves  #143

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@luotianchun Hi! Thanks for PR. Please change PR's title to the `docs: update instructions in Readme.md`

**Review by magicmatatjahu — APPROVED** [review]
I'm not a codeowner, but for me it looks good :)

**Comment by luotianchun** [comment]
> @luotianchun Hi! Thanks for PR. Please change PR's title to the `docs: update instructions in the Readme.md`

Oh sry, changed!

**Comment by magicmatatjahu** [comment]
@luotianchun No problem, thanks! :)

**Comment by ivangsa** [comment]
you can still open the Preview from the editor context-menu, plus there is also a preview icon,

image


(If you are creating an asyncapi file from scratch, the preview button may not appear until changes are detected)

**Comment by luotianchun** [comment]
> 

Oh yeah thanks I found it appear now, but before I selected in command palette, there is no preview icon or option in context-menu.

**Comment by luotianchun** [comment]
@ivangsa I have updated the description for this one. Thank you! :)

**Review by ivangsa — CHANGES_REQUESTED** [review]
It would be better if this screenshot is added to README.md instead of replacing existing one..

**Comment by luotianchun** [comment]
> It would be better if this screenshot is added to README.md instead of replacing existing one..

Oh I've changed back to the previous one, since I think we don't need to replace it. I will delete the screenshot I took or you want me add it in README?

**Review by ivangsa — APPROVED** [review]
lgt

**Pull request merged**
