### PR TITLE
fix: updated dependencies to latest version

### PR DESCRIPTION
**Pull request by hkaur008**
- [x]  Update dependencies to latest version

### CODE REVIEW

**Comment by hkaur008** [comment]
#31 @ivangsa @derberg 
I update the dependencies working over debugging !

**Comment by hkaur008** [comment]
**Errors I found on compiling the code** 

image

**Comment by derberg** [comment]
We can simplify things here. Basically we can remove `@asyncapi/generator` and `@asyncapi/html-template` and instead install `@asyncapi/web-component`  (version `1.0.0-next.23`) because looks how simple it is to use -> https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/web-component.md#usage-in-html-webpage simple HTML that just needs to be refreshed whenever some changes was done to the file.

I also suggest to not bump other dependencies to not complicate "figuring out why after update stuff are failing" 😄 

Lemme know if you need some help

**Comment by hkaur008** [comment]
I had removed  @asyncapi/generator and @asyncapi/html-template from dependencies

**Comment by derberg** [comment]
> I had removed @asyncapi/generator and @asyncapi/html-template from dependencies

I also suggest you do not bump all these different dependencies in this PR, there are many dependencies that are bumped a few major releases up. If something will fail you will have hard time to figure what

> Should I change basic react components to web-components ?

what do you mean

**Comment by hkaur008** [comment]
Okaayy

**Comment by hkaur008** [comment]
Let me know any work i need to do

**Comment by hkaur008** [comment]
Done ! @derberg  Have a look

**Comment by derberg** [comment]
@hkaur008 you did not update `package-lock.json`. Please `npm install` locally to get it refreshed with latest dependencies set and push to remote

**Comment by hkaur008** [comment]
> @hkaur008 you did not update `package-lock.json`. Please `npm install` locally to get it refreshed with latest dependencies set and push to remote

sure

**Review by derberg — COMMENTED** [review]
@hkaur008 now can you add some scripts that are failing CI checks, they are necessary but can just echo info that they arenot yet implemented. Please add below to `scripts` in `package.json`:
```
    "lint": "echo \"No linter configured yet\"",
    "generate:assets": "echo \"No assets to configure\"",
    "test": "echo \"No tests configured yet\"",
```

**Comment by hkaur008** [comment]
Okayy

**Comment by hkaur008** [comment]
@derberg all changes done

**Comment by derberg** [comment]
@hkaur008 now you need to remove all the logic related to `@asyncapi/generator` and `@asyncapi/html-template`. We do not need to run generator on a server every time to regenerate HTML with html-template. Whenever user modifies asyncapi file, it should be passed to HTML that uses the web-component, and the web component will cover the rendering of docs

**Comment by derberg** [comment]
@hkaur008 how is it going, need some help?

**Comment by hkaur008** [comment]
Yeah just understanding the code more, every time we are creating a server
and then asynci generator push html css .

But stuck on using Webcomponent as it requires some attributes schemeurl
etc and i m trying to understand how i can get these

**Comment by hkaur008** [comment]
Getting hard times using Webcomponent tag in typescript

**Comment by derberg** [comment]
Don't use `schemaUrl` as it requires from you hosting asyncapi file on a server so it can be fetched. Use `schema` property, as far as I remember you can pass asycapi document there as a string.

Do you need to use webcomponent in TS?

**Comment by hkaur008** [comment]
> yes i feel so 
image
Here in commented code, we are generating the server and using async API generator. or should I add the webcomponent directly in the `previwer.html` file and then pass that content in this server?

**Comment by hkaur008** [comment]
image
I can also add webcomponent here, I m just confused about where exactly I need to add it.
If you can help a little bit!

**Comment by derberg** [comment]
I think adding to `Preview.ts` makes more sense, as now it is just having HTML that has iframe to HTML file hosted by `PreviewServer.ts`. I did not look much in details but feels like `PreviewServer.ts` is not needed at all.

Also if you are familiar with React, I recommend just throwing web-component away and use React component directly.

**Comment by hkaur008** [comment]
Okay I familar with react so i m thinking to use that in previewer.ts

I was also confused why do we need preview server.ts .

One R there any commands to run the application. Except `npm run compile` ,
I think after the bugs are solved , then only i m able how exactly this
previewer works.
As i want to get more clear idea of it by looking at its working

**Comment by derberg** [comment]
> One R there any commands to run the application. Except `npm run compile` ,
I think after the bugs are solved , then only i m able how exactly this
previewer works.
As i want to get more clear idea of it by looking at its working

sorry I didn't get it, can you please rephrase it? do you mean you struggle with manual testing or?

**Comment by hkaur008** [comment]
Yeah, i was asking about manual testing

**Comment by hkaur008** [comment]
@derberg 
> I think adding to Preview.ts makes more sense, as now it is just having HTML that has an iframe to HTML file hosted by PreviewServer.ts
I got this.

image
A lot of code in `extension.ts` runs on `previewServer.ts` . A lot of refactoring is required after the introduction of react component as we don't need to restart the server after the update of the HTML file due to `AsyncApi-ReactComponent`.
But can have a little look in `extension.ts` file, tell about unwanted code and code that needs refactoring so that deletion of `previewServer.ts`  does not hampers things .

I m able to compile the vs code extension code using `npm run compile` but I was a little curious about actual output after running these files as I will be working with react-component , so I wanted to check output (extension and results of iframe).
So that code-refactoring doesn't hamper working of the extension

**Comment by derberg** [comment]
I'm not sure how in the end you added react there. If you managed to make it work through `Preview.ts` then from `extensions.ts` I assume you pass entire asyncapi file to this part
```
let inlinePreview = new Preview(previewServer.getUrl(fileName), fileName);
context.subscriptions.push(inlinePreview.disposable);
```

instead of iframe in `Preview.ts` and url, passed to the constructor, you pass asyncapi as string?
so the whole rest about `previewServer` just goes out as I can see, to become obsolete, right?

or I did not understand what you mean? maybe just push the code and it will be simpler.

btw, you are doing great stuff here ❤️ I have to push myself to learn more about vscode plugins as I never wrote one 😄

**Comment by hkaur008** [comment]
Cool, I check everything and do the refactoring

**Comment by derberg** [comment]
@hkaur008 yo, need help?

**Comment by hkaur008** [comment]
nope! just how I can see the finished product `vs-asyncapi-preview`?
It will take me less time to code then

**Comment by ivangsa** [comment]
hi all, I'm going to remove this extension from the marketplace because is getting bad reviews for being abandoned and it's published with my name

if you want to contact vscode Marketplace to transfer the extension to another publisher-id under AsyncAPI intiative that will give existing users/instalations automatic upgrades to the new one..

otherwise I will just remove the extension, and you can publish a new one anytime you are ready..

Just let me know if you need any help on my side regarding this..

**Comment by hkaur008** [comment]
nope! just how I can see the finished product `vs-asyncapi-preview`?
It will take me less time to code then

**Comment by ivangsa** [comment]
> nope! just how I can see the finished product `vs-asyncapi-preview`? It will take me less time to code then

@hkaur008 what do you mean by "see the finished product"?

As any vscode extension you can launch it in debug mode just pressing `F5` or you can use `vsce package` to create a *.vsix file you can install right clicking on the file inside vscode explorer

**Comment by ivangsa** [comment]
@hkaur008 I'm reviewing your branch and I don't see any code changes aside from some dependencies in package.json

**Comment by hkaur008** [comment]
cool! thanks for the leads.
I had not committed any changes yet

**Pull request closed without merging**
